name: C/C++ CI

on:
  push:
    branches: [ main ]
    tags:
      - 'commit/*'
  pull_request:
    types: [ opened, edited, reopened, review_requested ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt update; sudo apt install gcc -y
    - uses: actions/checkout@v2
    - name: Provide builder execution permission
      run: sudo chmod +x build.sh
    - name: Run build
      run: ./build.sh

